# Generated by Django 2.1.4 on 2019-01-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190117_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('icon', models.ImageField(null=True, upload_to='upload', verbose_name='头像')),
                ('resume', models.CharField(max_length=1000, null=True, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
    ]
